import type { Metadata } from "next";
import { Figtree } from 'next/font/google'
import "@/styles/globals.css";

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-figtree',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${figtree.variable}`}>
      <body
        className="font-figtree antialiased"
      >
        {children}
      </body>
    </html>
  );
}
